config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  # mount ActionCable.server, at: '/cable'
  root to: 'cars#index'

  get 'home/index'

  devise_for :users, skip: [:registrations]
  as :user do
    get 'users/edit', to: 'devise/registrations#edit', as: 'edit_user_registration'
    put 'users', to: 'devise/registrations#update', as: 'user_registration'
    delete 'users', to: 'devise/registrations#destroy'
  end

  resources :users, except: :index
  resources :cars, only: %i(index show)
  resources :orders

  namespace :admin do
    get '/', to: 'dashboards#index'
    resources :users
    resources :cars
  end

  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web, at: '/sidekiq', as: 'sidekiq'
  end
end

app/models/car.rb
class Car < ApplicationRecord
  validates :title, presence: true

  belongs_to :user
  has_one_attached :image
end

app/controllers/admin/cars_controller.rb
module Admin
  class CarsController < Admin::ApplicationController
    before_action :set_car, only: %i(show edit update destroy)

    def index
      @cars = Car.all
                 # .eager_load(:groups)
    end

    def show; end

    def new
      @car_form = ::CarForm.new
    end

    def edit
      @car_form = ::CarForm.new(id: @car.id)
    end

    def create
      @car_form = ::CarForm.new(car_form_params.merge(current_user: current_user))
      if car = @car_form.save
        # image attach from ActiveStorage doesn't work in form object yet
        car.image.attach(params[:car_form][:image]) if params[:car_form][:image].present?
        redirect_to admin_cars_path, notice: 'Car was successfully created.'
      else
        render :new
      end
    end

    def update
      @car_form = ::CarForm.new(car_form_params.merge(current_user: current_user, id: @car.id))
      if @car_form.update
        redirect_to admin_cars_path, notice: 'Car was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @car.destroy
      respond_to do |format|
        format.html { redirect_to admin_cars_url, notice: 'Car was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private

    def set_car
      @car = Car.find(params[:id])
    end

    def car_params
      params.require(:car).permit(:title, :description)
    end

    def car_form_params
      params.require(:car_form).permit(:title, :description, :image)
    end
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    @cars = Car.all
              # .joins(:groups).eager_load(:image_attachment)
               # .where('groups.id IN (?)', current_user.groups.pluck(:id))
    authorize @cars
  end

  def show
    @car = Car.find_by(id: params[:id])
    CarViewsService.new(@car, current_user).perform
    authorize @car
  end
end

app/helpers/cars_helper.rb
module CarsHelper
  def car_form_path(car)
    car.present? ? admin_car_path(@car) : admin_cars_path
  end

  def car_form_method(car)
    car.present? ? :put : :post
  end

  def car_form_button(car)
    car.present? ? 'Edit' : 'New'
  end

  def total_users(group)
    # post.groups.map { |item| item.users.count }.sum
  end

  def views_percents(car)
    1
    # return '-' if post.views_info.empty? || total_users(post).zero?
    # "#{100 * post.views_info.length / total_users(post)} %"
  end
end

app/views/admin/cars/_form.html.slim
= form_for(@car_form, url: car_form_path(@car), method: car_form_method(@car), html: { class: 'form-horizontal' }) do |f|
  .card-header
    i.fa.fa-align-justify
    strong
      = title if defined? title
  .card-body
    - if @car_form.errors.any?
      #error_explanation
        h2 = "#{pluralize(@car_form.errors.count, "error")} prohibited this car from being saved:"
        ul
          - @car_form.errors.full_messages.each do |message|
            li = message
    .form-group.row
      label.col-md-3.col-form-label Title
      .col-md-9
        = f.text_field :title, class: 'form-control'
    .form-group.row
      label.col-md-3.col-form-label Description
      .col-md-9
        = f.text_area :description, class: 'form-control'
    .form-group.row
      label.col-md-3.col-form-label Image
      .col-md-9
        = f.file_field :image
    / .form-group.row
    /   label.col-md-3.col-form-label Group with permission
    /   .col-md-9
    /     = f.collection_check_boxes :group_ids, Group.all, :id, :name do |g|
    /       .form-check.checkbox
    /         = g.check_box class: 'form-check-input'
    /         label.form-check-label = g.text
  .card-footer
    = f.submit "#{car_form_button(@car)} car", class: 'btn btn-sm btn-primary' do
      i.fa.fa-dot-circle-o
    = link_to admin_cars_path, class: 'btn btn-sm btn-danger' do
      i.fa.fa-ban
      | Reset

app/views/admin/cars/edit.html.slim
.animated.fadeIn
  .row
    .col-lg-12
      .card
        == render partial: 'form', locals: { title: 'Edit car' }

/ => link_to 'Show', admin_car_path(@car)
/ '|
/ =< link_to 'Back', admin_car_path

app/views/admin/cars/index.html.slim
- content_for(:additional_scripts) do
  script src='https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js'
  script src='https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap4.min.js'
  = javascript_include_tag 'datatable'

- content_for(:additional_styles) do
  link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/dataTables.bootstrap4.min.css"

.animated.fadeIn
  .row
    .col-lg-12
      .card
        .card-header
          i.fa.fa-align-justify
          | Cars list
          .card-actions
            = link_to new_admin_car_path do
              i.icon-plus
        .card-body
          table#datatable.table.table-striped.table-bordered style="width:100%"
            thead
              tr
                th Title
                th Description
                th Total users
                th Views stats
                th Actions
            tbody
              - @cars.each do |car|
                - cache car
                  tr
                    td = car.title.truncate(25, omission: '...')
                    td = car.description.truncate(150, omission: '...')
                    td = total_users(car)
                    td class="#{car.id}" = views_percents(car)

                    td.actions
                      = link_to 'Show', admin_car_path(car)
                      = link_to 'Edit', edit_admin_car_path(car)
                      = link_to 'Destroy', admin_car_path(car), data: { confirm: 'Are you sure?'}, method: :delete
            tfoot
              tr
                th Title
                th Description
                th Total users
                th Views stats
                th Actions

app/views/admin/cars/new.html.slim
.animated.fadeIn
  .row
    .col-lg-12
      .card
        == render partial: 'form', locals: { title: 'New car' }

app/views/admin/cars/show.html.slim
.animated.fadeIn
  .row
    .col-lg-12
      .card
        .card-header
          i.fa.fa-align-justify
          | New car
        .card-body
          p#notice = notice

          p
            strong Title:
            = @car.title
          p
            strong Description:
            = @car.description

          => link_to 'Edit', edit_admin_car_path(@car)
          '|
          =< link_to 'Back', admin_cars_path