config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  # mount ActionCable.server, at: '/cable'
  root to: 'cars#index'

  get 'home/index'

  devise_for :users, skip: [:registrations]
  as :user do
    get 'users/edit', to: 'devise/registrations#edit', as: 'edit_user_registration'
    put 'users', to: 'devise/registrations#update', as: 'user_registration'
    delete 'users', to: 'devise/registrations#destroy'
  end

  resources :users, except: :index
  resources :cars, only: %i(index show)
  resources :orders

  namespace :admin do
    get '/', to: 'dashboards#index'
    resources :users
    resources :cars
  end

  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web, at: '/sidekiq', as: 'sidekiq'
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_one :car

  validates :car_id, presence: true
  validates :user_id, presence: true
  validates :start_at, presence: true
  validates :end_at, presence: true
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: %i[ show edit update destroy ]

  # GET /orders or /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1 or /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders or /orders.json
  def create
    @order = Order.new(order_params.merge(user_id: current_user.id))

    respond_to do |format|
      if @order.save
        format.html { redirect_to cars_path, notice: "Order was successfully created." }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1 or /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: "Order was successfully updated." }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1 or /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: "Order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_params
      params.require(:order).permit(:start_at, :end_at, :user_id, :car_id)
    end
end

app/views/orders/_form.html.slim
= form_for @order do |f|
  - if @order.errors.any?
    #error_explanation
      h2 = "#{pluralize(@order.errors.count, 'error')} prohibited this order from being saved:"
      ul
        - @order.errors.full_messages.each do |message|
          li = message

  .form-group.row
    label.col-md-3.col-form-label Date rent starts
    .col-md-9
      = f.datetime_field :start_at, min: Date.today, class: 'form-control'
  .form-group.row
    label.col-md-3.col-form-label Date rent finishes
    .col-md-9
      = f.datetime_field :end_at, min: Date.today , class: 'form-control'
  = f.hidden_field :car_id, value: params[:car].to_i
  .actions = f.submit

app/views/orders/edit.html.slim
h1 Editing order

== render 'form'

=> link_to 'Show', @order
'|
=< link_to 'Back', orders_path

app/views/orders/index.html.slim
h1 Listing orders

table
  thead
    tr
      th
      th
      th

  tbody
    - @orders.each do |order|
      tr
        td = link_to 'Show', order
        td = link_to 'Edit', edit_order_path(order)
        td = link_to 'Destroy', order, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Order', new_order_path

app/views/orders/new.html.slim
h1 New order

== render 'form'

= link_to 'Back', orders_path

app/views/orders/show.html.slim
p#notice = notice

=> link_to 'Edit', edit_order_path(@order)
'|
=< link_to 'Back', orders_path