config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  # mount ActionCable.server, at: '/cable'
  root to: 'cars#index'

  get 'home/index'

  devise_for :users, skip: [:registrations]
  as :user do
    get 'users/edit', to: 'devise/registrations#edit', as: 'edit_user_registration'
    put 'users', to: 'devise/registrations#update', as: 'user_registration'
    delete 'users', to: 'devise/registrations#destroy'
  end

  resources :users, except: :index
  resources :cars, only: %i(index show)
  resources :orders

  namespace :admin do
    get '/', to: 'dashboards#index'
    resources :users
    resources :cars
  end

  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web, at: '/sidekiq', as: 'sidekiq'
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  #
  #
  devise :registerable, :invitable, :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  enum role: %i(user admin)

  validates :email, presence: true, uniqueness: true

  has_many :cars
  has_many :orders
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    before_action :set_user, only: %i(show edit update destroy)

    def index
      @users = User.where.not(id: current_user.id)
    end

    def show; end

    def new
      @user_form = ::UserForm.new
    end

    def edit
      @user_form = ::UserForm.new(id: @user.id)
    end

    def create
      @user_form = ::UserForm.new(user_form_params)
      if @user_form.save
        redirect_to admin_users_path, notice: 'User was successfully created.'
      else
        render :new
      end
    end

    def update
      @user_form = ::UserForm.new(user_form_params.merge(id: @user.id))
      if @user_form.update
        redirect_to admin_users_path, notice: 'User was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @user.destroy
      respond_to do |format|
        format.html { redirect_to admin_users_path, notice: 'user was successfully destroyed' }
        format.json { head :no_content }
      end
    end

    private

    def set_user
      @user = User.find_by_id(params[:id])
    end

    def user_params
      params.require(:user).permit(:email, :first_name, :last_name, :role)
    end

    def user_form_params
      params.require(:user_form).permit(:email, :first_name, :last_name, :role, group_ids: [])
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i(edit show update)

  def show
    authorize @user
  end

  def edit; end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_path(@user), notice: 'Profile was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  private

  def set_user
    @user = User.find_by_id(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def form_path(user)
    user.present? ? admin_user_path(user) : admin_users_path
  end

  def form_method(user)
    user.present? ? :put : :post
  end

  def form_button(user)
    user.present? ? 'Edit' : 'New'
  end
end

app/views/admin/users/_edit.html.slim
.modal-dialog role="document"
  .modal-content
    = render partial: 'form', locals: { user: @user, title: 'Edit user' }

app/views/admin/users/_form.html.slim
.modal-header
  h5#modalLabel.modal-title = title if defined? title

  button.close aria-label="Close" data-dismiss="modal" type="button"
    span aria-hidden="true"  &times;
= form_for(@user_form, url: form_path(@user), method: form_method(@user), html: { class: 'form-horizontal' }) do |f|
  .modal-body
    .form-group.row
      label.col-md-3.col-form-label Email
      .col-md-9
        = f.email_field :email, class: 'form-control'
    .form-group.row
      label.col-md-3.col-form-label First name
      .col-md-9
        = f.text_field :first_name, class: 'form-control'
    .form-group.row
      label.col-md-3.col-form-label Last name
      .col-md-9
        = f.text_field :last_name, class: 'form-control'
    .form-group.row
      label.col-md-3.col-form-label Role
      .col-md-9
        = f.select(:role, User.roles.keys.to_a, {}, {class: 'form-control'})
  .modal-footer
    button.btn.btn-secondary data-dismiss="modal" type="button"  Close
    = f.submit "#{form_button(@user)} user", class: 'btn btn-primary'

app/views/admin/users/_new.html.slim
.modal-dialog role="document"
  .modal-content
    = render partial: 'form', locals: { user: @user, title: 'Create new user' }

app/views/admin/users/edit.js.erb
$('#modal').html("<%= j render 'edit' %>");

app/views/admin/users/index.html.slim
.animated.fadeIn
  .row
    .col-lg-12
      .card
        .card-header
          i.fa.fa-align-justify
          | Users list
          .card-actions
            = link_to new_admin_user_path, { remote: true, 'data-toggle': 'modal', 'data-target': '#modal' } do
              i.icon-plus
        .card-body
          table.table.table-responsive-sm
            thead
              tr
                th User info
                th Date registered
                th Role
                th Actions
            tbody
              - @users.each do |user|
                - cache user
                  tr
                    td = user.email
                    td = user.created_at
                    td = user.role
                    td
                      = link_to 'Edit', edit_admin_user_path(user), { remote: true, 'data-toggle': 'modal', 'data-target': '#modal', class: 'm-10' }
                      = link_to 'Destroy', admin_user_path(user),
                                           method: :delete,
                                           data: { confirm: 'Are you sure?' },
                                           class: 'm-10'

app/views/admin/users/new.js.erb
$('#modal').html("<%= j render 'new' %>");