config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  # mount ActionCable.server, at: '/cable'
  root to: 'cars#index'

  get 'home/index'

  devise_for :users, skip: [:registrations]
  as :user do
    get 'users/edit', to: 'devise/registrations#edit', as: 'edit_user_registration'
    put 'users', to: 'devise/registrations#update', as: 'user_registration'
    delete 'users', to: 'devise/registrations#destroy'
  end

  resources :users, except: :index
  resources :cars, only: %i(index show)
  resources :orders

  namespace :admin do
    get '/', to: 'dashboards#index'
    resources :users
    resources :cars
  end

  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web, at: '/sidekiq', as: 'sidekiq'
  end
end

app/views/layouts/_head.html.slim
head
  meta charset="utf-8"
  meta http-equiv="X-UA-Compatible" content="IE=edge"
  meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"
  meta name="description" content="Service to rent a car"
  meta name="author" content="Anastasia"
  meta name="keyword" content="Rent a car"
  title = "Rent a Car#{yield(:title)}"
  link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.1.0/css/flag-icon.min.css"
  link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
  link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.4.1/css/simple-line-icons.css"
  = yield(:additional_styles) if yield(:additional_styles).present?
  = stylesheet_link_tag 'application', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = render 'layouts/scripts'
  = csrf_meta_tags
  = action_cable_meta_tag

app/views/layouts/_header.html.slim
header.app-header.navbar
  button.navbar-toggler.mobile-sidebar-toggler.d-lg-none.mr-auto type="button"
    span.navbar-toggler-icon
  = link_to root_path, class: 'logo' do
    h3 Rent a Car
  / a.navbar-brand href="#{root_path}"
  - if current_user.admin?
    button.navbar-toggler.sidebar-toggler.d-md-down-none type="button"
      span.navbar-toggler-icon
  - if current_user.user?
    ul.nav.navbar-nav.d-md-down-none
      / li.nav-item.px-3
      /   a.nav-link href="#"  Dashboard
      li.nav-item.px-3
        = link_to 'Cars', cars_path
  ul.nav.navbar-nav.ml-auto
    li.nav-item.dropdown
      a.nav-link aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#" role="button"
        span.user_name = current_user.email

      .dropdown-menu.dropdown-menu-right
        = link_to user_path(current_user), class: 'dropdown-item' do
          i.fa.fa-user
          | Profile

        = link_to destroy_user_session_path, method: :delete, class: 'dropdown-item' do
          i.fa.fa-lock
          | Logout

app/views/layouts/_left_sidebar.html.slim
- if current_user.admin?
  .sidebar
    nav.sidebar-nav
      ul.nav
        li.nav-item
          = link_to admin_path, class: 'nav-link' do
            i.icon-speedometer
            | Dashboard
            / span.badge.badge-primary NEW
        li.nav-item
          = link_to admin_cars_path, class: 'nav-link' do
            i.icon-pencil
            | Cars
        li.nav-item
          = link_to admin_users_path, class: 'nav-link' do
            i.icon-people
            | Users


    button.sidebar-minimizer.brand-minimizer type='button'

app/views/layouts/_scripts.html.slim
script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"
script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"

app/views/layouts/application.html.slim
doctype html
html
  = render 'layouts/head'
  body.app.header-fixed.aside-menu-fixed.sidebar-fixed.aside-menu-hidden class=[current_user.user? ? 'sidebar-hidden' : 'sidebar-minimized']
    = render 'layouts/header'
    .app-body
      = render 'layouts/left_sidebar'
      /! Main content
      main.main
        ol.breadcrumb
          li.breadcrumb-menu.d-md-down-none
            .btn-group aria-label=("Button group") role="group"
        .container-fluid
          = flash_messages
          #ui-view
            .animated.fadeIn
              = yield
        /! Modal
        #modal.modal.fade aria-hidden="true" aria-labelledby="exampleModalLabel" role="dialog" tabindex="-1"
          .modal-dialog role="document"
            .modal-content
    footer.app-footer
      span
        / a href="#" Anastasia
        / | &nbsp;&copy; 2018 Anastasia.
      span.ml-auto
        / | Powered by
        / a href="#"  Anastasia
    script src="https://cdnjs.cloudflare.com/ajax/libs/pace/1.0.2/pace.min.js"
    /! Plugins and scripts required by all views
    / script src="node_modules/chart.js/dist/Chart.min.js"
    = javascript_include_tag 'app'
    = yield(:additional_scripts) if yield(:additional_scripts).present?

app/views/layouts/devise.html.slim
doctype html
html lang="en"
  = render 'layouts/head'
  body.app.flex-row.align-items-center
    .container
      = flash_messages
      .row.justify-content-center
        = yield